/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DB.StudentDB;
import model.Student;
import model.StudentBuilder;
import model.employee.employee;

/**
 *
 * @author USER
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setTitle("student Page");
        setResizable(false);
        loadTabel();
    }
     StudentDB sdb = new StudentDB();
    int id = 0;
    
     // for load tabel
    private void loadAllData(List<Student> list) {
    DefaultTableModel dtm = (DefaultTableModel) tabel.getModel();
    dtm.setRowCount(0);
    
    for(Student s : list){
    Vector v = new Vector();
    v.add(s.getId());
    v.add(s.getName());
    v.add(s.getAge());
    v.add(s.getGender());
    v.add(s.getMobileNb());
    v.add(s.getGrade());
    dtm.addRow(v);
  }
    }
    public void loadTabel(){
          StudentDB sdb1 = new StudentDB();
    List l = sdb1.loadData();
    loadAllData(l);
    }
    public void clearFielf(){
      edtname.setText("");
        edtage.setText("");
        edtgrade.setText("");
        edtmnmb.setText("");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        edtname = new javax.swing.JTextField();
        edtage = new javax.swing.JTextField();
        edtmnmb = new javax.swing.JTextField();
        edtgrade = new javax.swing.JTextField();
        edtgender = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btndelet = new javax.swing.JButton();
        btnCleaer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 150, 148));
        jPanel1.setForeground(new java.awt.Color(0, 150, 148));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SCHOOL SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1214, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 150, 148));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtnameActionPerformed(evt);
            }
        });
        jPanel2.add(edtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 35, 172, -1));
        jPanel2.add(edtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 176, 172, -1));
        jPanel2.add(edtmnmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 246, 172, -1));

        edtgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtgradeActionPerformed(evt);
            }
        });
        jPanel2.add(edtgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 314, 172, -1));

        edtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jPanel2.add(edtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 172, -1));

        btnadd.setBackground(new java.awt.Color(0, 150, 148));
        btnadd.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("ADD");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 355, 128, 62));

        btnUpdate.setBackground(new java.awt.Color(0, 150, 148));
        btnUpdate.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 355, 120, 62));

        btndelet.setBackground(new java.awt.Color(0, 150, 148));
        btndelet.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btndelet.setForeground(new java.awt.Color(255, 255, 255));
        btndelet.setText("DELETE");
        btndelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletActionPerformed(evt);
            }
        });
        jPanel2.add(btndelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 447, 128, 66));

        btnCleaer.setBackground(new java.awt.Color(0, 150, 148));
        btnCleaer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnCleaer.setForeground(new java.awt.Color(255, 255, 255));
        btnCleaer.setText("CLEAR");
        btnCleaer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleaerActionPerformed(evt);
            }
        });
        jPanel2.add(btnCleaer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 447, 120, 66));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 150, 148));
        jLabel2.setText("NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 33, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 150, 148));
        jLabel3.setText("GENDER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 105, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 150, 148));
        jLabel4.setText("AGE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 150, 148));
        jLabel5.setText("MOBILE NUMBER");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 244, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 150, 148));
        jLabel6.setText("GRADE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 312, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 150, 148));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 129, 640, 540));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "name", "age", "gender", "mobile number", "grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 560, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String name = edtname.getText();
        String gender = (String) edtgender.getSelectedItem();
        int age = Integer.valueOf(edtage.getText()) ;
        int mobilemb = Integer.valueOf(edtmnmb.getText());
        int grade = Integer.valueOf(edtgrade.getText());
        
        
        // student 
        
        Student s = new StudentBuilder(id,name).setData(age ,gender , mobilemb , grade).build();
        
        sdb.insert(s);
        loadTabel();
        clearFielf();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         // TODO add your handling code here:
        String name = edtname.getText();
        String gender = (String) edtgender.getSelectedItem();
        int age = Integer.valueOf(edtage.getText()) ;
        int mobilemb = Integer.valueOf(edtmnmb.getText());
        int grade = Integer.valueOf(edtgrade.getText());
        Student st = new StudentBuilder(id,name).setData(age ,gender , mobilemb , grade).build();
         sdb.updatData(st);
        loadTabel();
        clearFielf();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletActionPerformed
       // TODO add your handling code here:
        sdb.deleteData(id);
        loadTabel();
        clearFielf();
    }//GEN-LAST:event_btndeletActionPerformed

    private void btnCleaerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleaerActionPerformed
        // TODO add your handling code here:
        clearFielf();
    }//GEN-LAST:event_btnCleaerActionPerformed

    private void edtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtnameActionPerformed

    private void edtgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtgradeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homePage1 h = new homePage1();
        this.hide();
        h.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
       // TODO add your handling code here:
       int row = tabel.getSelectedRow();
        if(row < 0 ){
        JOptionPane.showMessageDialog(null, "pleas select any recorde from the tabel");
        }else{
         id = (int) tabel.getValueAt(row, 0);
        Student s = sdb.retutnAllDataToField(id);
      //  if(s == null)
      //  JOptionPane.showMessageDialog(null, "s not creat");
        edtgrade.setText(Integer.toString(s.getGrade()));
        edtname.setText(s.getName());
        
        
        edtage.setText(Integer.toString(s.getAge()));
        edtmnmb.setText(Integer.toString(s.getMobileNb()));
        }
    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleaer;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelet;
    private javax.swing.JTextField edtage;
    private javax.swing.JComboBox<String> edtgender;
    private javax.swing.JTextField edtgrade;
    private javax.swing.JTextField edtmnmb;
    private javax.swing.JTextField edtname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
