/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author USER
 */
public class homePage1 extends javax.swing.JFrame {

    /**
     * Creates new form homePage1
     */
    public homePage1() {
        initComponents();
        this.setTitle("Home Page");
        setResizable(false);
        btnteacher.setVisible(false);
        btnadministrator.setVisible(false);
        btnsupport.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnstudent = new javax.swing.JButton();
        btnemployee = new javax.swing.JButton();
        btnadministrator = new javax.swing.JButton();
        btnteacher = new javax.swing.JButton();
        btnsupport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 150, 148));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HOME PAGE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnstudent.setBackground(new java.awt.Color(0, 150, 148));
        btnstudent.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnstudent.setForeground(new java.awt.Color(255, 255, 255));
        btnstudent.setText("STUDENTS");
        btnstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentActionPerformed(evt);
            }
        });
        jPanel2.add(btnstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        btnemployee.setBackground(new java.awt.Color(0, 150, 148));
        btnemployee.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnemployee.setForeground(new java.awt.Color(255, 255, 255));
        btnemployee.setText("EMPLOYES");
        btnemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btnemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        btnadministrator.setBackground(new java.awt.Color(0, 150, 148));
        btnadministrator.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnadministrator.setForeground(new java.awt.Color(255, 255, 255));
        btnadministrator.setText("ADMINISTRATORS");
        btnadministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadministratorActionPerformed(evt);
            }
        });
        jPanel2.add(btnadministrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 162, 220, 40));

        btnteacher.setBackground(new java.awt.Color(0, 150, 148));
        btnteacher.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        btnteacher.setForeground(new java.awt.Color(255, 255, 255));
        btnteacher.setText("TEACHERS");
        btnteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnteacherActionPerformed(evt);
            }
        });
        jPanel2.add(btnteacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 220, 40));

        btnsupport.setBackground(new java.awt.Color(0, 150, 148));
        btnsupport.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        btnsupport.setForeground(new java.awt.Color(255, 255, 255));
        btnsupport.setText("support stuff");
        btnsupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupportActionPerformed(evt);
            }
        });
        jPanel2.add(btnsupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 303, 220, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeeActionPerformed
        // TODO add your handling code here:
        btnteacher.setVisible(true);
        btnadministrator.setVisible(true);
        btnsupport.setVisible(true);
        
    }//GEN-LAST:event_btnemployeeActionPerformed

    private void btnstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentActionPerformed
        HomePage h = new HomePage();
        h.show();
        this.hide();
    }//GEN-LAST:event_btnstudentActionPerformed

    private void btnteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnteacherActionPerformed
        teacherPage t = new teacherPage();
        t.show();
        this.hide();
    }//GEN-LAST:event_btnteacherActionPerformed

    private void btnadministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadministratorActionPerformed
        administratorPage a = new administratorPage();
        a.show();
        this.hide();
    }//GEN-LAST:event_btnadministratorActionPerformed

    private void btnsupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupportActionPerformed
        // TODO add your handling code here:
        supportstuffPage a = new supportstuffPage();
        a.show();
        this.hide();
    }//GEN-LAST:event_btnsupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadministrator;
    private javax.swing.JButton btnemployee;
    private javax.swing.JButton btnstudent;
    private javax.swing.JButton btnsupport;
    private javax.swing.JButton btnteacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
